# Generated by Django 5.0 on 2023-12-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='верификация почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='07791790058986903', max_length=100, verbose_name='token'),
        ),
    ]
