# Generated by Django 5.0 on 2023-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, default='static/img', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
