# Generated by Django 5.0 on 2023-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, default='/static/img/photo.png', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
