# Generated by Django 4.2.7 on 2023-12-03 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_product_discription_product_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_last_change',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='цена за штуку'),
        ),
    ]
